name: scrolling_navbar
description: A simple and easy to implement feature
version: 0.0.3
homepage: https://teamcrushing.it
repository: https://github.com/Team-Crushing-It/scrolling_navbar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

